 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/private_messages", type: :request do
  
  # PrivateMessage. As you add validations to PrivateMessage, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      PrivateMessage.create! valid_attributes
      get private_messages_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      private_message = PrivateMessage.create! valid_attributes
      get private_message_url(private_message)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_private_message_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      private_message = PrivateMessage.create! valid_attributes
      get edit_private_message_url(private_message)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new PrivateMessage" do
        expect {
          post private_messages_url, params: { private_message: valid_attributes }
        }.to change(PrivateMessage, :count).by(1)
      end

      it "redirects to the created private_message" do
        post private_messages_url, params: { private_message: valid_attributes }
        expect(response).to redirect_to(private_message_url(PrivateMessage.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new PrivateMessage" do
        expect {
          post private_messages_url, params: { private_message: invalid_attributes }
        }.to change(PrivateMessage, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post private_messages_url, params: { private_message: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested private_message" do
        private_message = PrivateMessage.create! valid_attributes
        patch private_message_url(private_message), params: { private_message: new_attributes }
        private_message.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the private_message" do
        private_message = PrivateMessage.create! valid_attributes
        patch private_message_url(private_message), params: { private_message: new_attributes }
        private_message.reload
        expect(response).to redirect_to(private_message_url(private_message))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        private_message = PrivateMessage.create! valid_attributes
        patch private_message_url(private_message), params: { private_message: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested private_message" do
      private_message = PrivateMessage.create! valid_attributes
      expect {
        delete private_message_url(private_message)
      }.to change(PrivateMessage, :count).by(-1)
    end

    it "redirects to the private_messages list" do
      private_message = PrivateMessage.create! valid_attributes
      delete private_message_url(private_message)
      expect(response).to redirect_to(private_messages_url)
    end
  end
end
