development:
  adapter: redis
  # url: redis://serene-sands-99395.herokuapp.com:6379/1
  url: redis://localhost:6379/1

test:
  adapter: test

production:
  adapter: redis
  # url: <%= ENV.fetch("REDIS_URL") { "redis://serene-sands-99395.herokuapp.com:6379/1" } %>
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379:6379/1" } %>
  channel_prefix: chat_room_production
