development:
  adapter: redis
<<<<<<< Updated upstream
  # url: redis://pacific-bayou-73271.herokuapp.com:6379/1
=======
  #url: redis://pacific-bayou-73271.herokuapp.com:6379/1
>>>>>>> Stashed changes
  url: redis://localhost:6379/1

test:
  adapter: test

production:
  adapter: redis
<<<<<<< Updated upstream
  # url: <%= ENV.fetch("REDIS_URL") { "redis://pacific-bayou-73271.herokuapp.com:6379:6379/1" } %>
=======
  #url: <%= ENV.fetch("REDIS_URL") { "redis://pacific-bayou-73271.herokuapp.com:6379:6379/1" } %>
>>>>>>> Stashed changes
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379:6379/1" } %>
  channel_prefix: chat_room_production
